name: Go

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: github.com/kohofinancial/errors

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Test
        run: |
          cd github.com/kohofinancial/errors
          go test -v ./...