name: Go

on:
  - push

jobs:
  Test:
    runs-on: ubuntu-20.04

    defaults:
      run:
        working-directory: github.com/kohofinancial/errors

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Debug
        run: pwd && ls -lahG

      - name: Setup Go
        uses: actions/setup-go@v3.3.0
        with:
          go-version-file: go.mod

      # On this stage, we need the path to be the Github repository path for proper stack traces.
      - name: Test
        run: go test -v ./...
