name: Go

on:
  - push

jobs:
  Test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3.0.2
        with:
          path: github.com/kohofinancial/errors

      - name: Setup Go
        uses: actions/setup-go@v3.3.0
        with:
          go-version-file: go.mod

      # On this stage, we need the path to be the Github repository path for proper stack traces.
      - name: Test
        run: |
          cd github.com/kohofinancial/errors
          go test -v ./...
