name: 'Close stale PRs'
on:
  schedule:
    - cron: '15 9 * * 1-5'

jobs:
  stale:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/stale@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: 'This PR is stale because it has been open 7 days with no activity. Please remove stale label or comment or this will be closed in 7 days.'
          close-pr-message: 'This PR was closed because it has been stalled for 7 days with no activity.'
          days-before-pr-stale: 7
          days-before-pr-close: 7
          delete-branch: true